Casper glossary
CasperLabs/docs pull request #124
Opened 2021-02-21 01:16 UTC by ipopescu

Add a glossary to the docs. Work in progress.

2021-02-22 17:57 UTC, MParlikar requested changes
Great job.  Much needed.

2021-02-22 17:57 UTC, MParlikar commented on glossary/S.rst
> +The reward mechanism by which we mint new tokens and distribute them to validators.
'The reward mechanism by which validators are rewarded for participating in consensus.  New tokens are minted and given to validators'

2021-02-22 17:57 UTC, MParlikar commented on glossary/N.rst
> +* **Stand-alone node**: a mode for starting the node in which it does not attempt to connect to another node that is already part of a P2P network (called the bootstrap node). This mode is useful for
I do not believe this is supported.   A stand alone Casper node will panic.

2021-02-22 17:57 UTC, MParlikar commented on glossary/N.rst
> +#. COMM - contains the logic for message passing between nodes on the network (via TCP) as well as discovering new peers (via Kademlia)
We do not have Kademlia node discover right now.

2021-02-22 17:57 UTC, MParlikar commented on glossary/N.rst
> +#. Consensus - contains the logic to update the `blockstore <B.html#blockstore>`_ so that agreement is maintained between nodes. It also contains logic to detect when `deploys <D.html#deploy>`_ commu
block store and global state.  We do not support commutation (paralelism) at this time

2021-02-22 17:57 UTC, MParlikar commented on glossary/N.rst
> +* **Bootstrap node**: a peer node on the P2P network that contains the logic for message passing between nodes on the network (via TCP) and discovering new peers so that they may join the network.
We call these 'trusted nodes' I believe in config.toml.  It could be any node on the network that can be trusted.

2021-02-22 17:57 UTC, MParlikar commented on glossary/N.rst
> +* **Read-only node**: a type of node on the network that receives and processes blocks but does not create blocks and is not a validator. It is otherwise a fully functioning node, following the conse
We should change this to 'Bonded and Unbonded nodes' - All nodes have to start up the same way.  The difference is whether the node becomes bonded  through a separate bid to the auction contract.  In this way, we are pretty different!

2021-02-22 17:57 UTC, MParlikar commented on glossary/N.rst
> +In `node <N.html#node>`_ COMM - contains the logic for message passing between nodes on the network (via TCP) as well as discovering new peers (via Kademlia).
We call these 'trusted nodes'.  Feel free to add the definition here.

2021-02-22 17:57 UTC, MParlikar commented on glossary/P.rst
> +The process of following the `consensus <C.html#consensus>`_ algorithm. The primary participants are `validators <V.html#validators>`_.
Please also include 'delegators' for Casper consensus. Delegators (stakers) add weight to validators, and can be the deciding factor on who is in or out..

2021-02-22 17:57 UTC, MParlikar commented on glossary/P.rst
> +
Casper also has the notion of payment code separate from Session code.

2021-02-22 17:57 UTC, MParlikar commented on glossary/S.rst
> +A person that deposits tokens in the `proof-of-stake <P.html#proof-of-stake>`_ contract. Sometimes a staker is also a `validator <V.html#validator>`_. Stakers take on the slashing risk in exchange fo
A staker can also be a delegator

2021-02-22 17:57 UTC, MParlikar commented on glossary/P.rst
> +
Include private key  (we like to call them secret keys in our docs)

2021-02-22 17:57 UTC, MParlikar commented on glossary/T.rst
> +*  **Signature** – [mandatory] must be over (payment code, session code, conversion rate, nonce) to ensure a valid execution can only do the operations the user wants to be done.
Include that the signature is done via a private or secret key

2021-02-22 17:57 UTC, MParlikar commented on glossary/U.rst
> +Withdrawing money from the Proof-of-Stake (PoS) contract and possibly ceasing to be a validator.
Auction contract.  Done by 'withdraw bid'

2021-02-22 17:57 UTC, MParlikar commented on glossary/U.rst
> +The unbonding request is a transaction that informs the PoS contract that the sender wants to decrease their deposit. In the next booking block, only the decreased deposit is considered when determin
Auction contract.

2021-02-22 17:57 UTC, MParlikar commented on glossary/U.rst
> +However, the amount only gets transferred to the sender several weeks later, after the unbonding period. If during that period their node exhibits a fault, the unbonded amount can still be slashed.
remove 'several weeks later'

2021-02-22 17:57 UTC, MParlikar commented on glossary/V.rst
> +Validators are bonded because they are responsible for progressing the system's state as clients use it (e.g., sending deploys). Validators and `stakers <S.html#staker>`_ can lose their bond (be slas
paid 'for'

2021-02-24 13:35 UTC, ipopescu commented on glossary/B.rst
> +Depositing money in the Proof-of-Stake (PoS) contract and trying to become a `staker <S.html#staker>`_. The bonding request is a transaction that transfers tokens to the PoS contract. In the next `bo
Updated to: "Depositing money in the auction contract and try to become a staker. The bonding request is a transaction that transfers tokens to the auction contract. In the next booking block, a new set of validators is determined, with weights according to their deposits. This new set becomes active in the era(s) using that booking block."

2021-02-24 13:37 UTC, ipopescu commented on glossary/A.rst
> +Is a TypeScript-based programming language (essentially JavaScript with static types) that is optimized for WebAssembly and compiled to WebAssembly using asc, the reference AssemblyScript compiler. I
Added a new term: 
**Auction**
The auction determines the composition of the validator set for each era of the protocol. It is a "first-price" auction (where winning bids become stakes) with a fixed number of spots, chosen to balance security with performance. Because rewards are proportional to the stake, it is expected that this competitive mechanism will provide a powerful impetus for staking as many tokens as possible.

2021-02-24 13:41 UTC, ipopescu commented on glossary/P.rst
> +
Yes, added proto block.

2021-02-24 13:42 UTC, ipopescu commented on glossary/S.rst
> +The reward mechanism by which we mint new tokens and distribute them to validators.
Updated

2021-02-24 13:44 UTC, ipopescu commented on glossary/N.rst
> +* **Stand-alone node**: a mode for starting the node in which it does not attempt to connect to another node that is already part of a P2P network (called the bootstrap node). This mode is useful for
Removed the standalone node; however, I kept the bootstrap and read-only nodes.

2021-02-24 13:46 UTC, ipopescu commented on glossary/T.rst
> +*  **Signature** – [mandatory] must be over (payment code, session code, conversion rate, nonce) to ensure a valid execution can only do the operations the user wants to be done.
Added

2021-02-24 13:47 UTC, ipopescu commented on glossary/U.rst
> +The unbonding request is a transaction that informs the PoS contract that the sender wants to decrease their deposit. In the next booking block, only the decreased deposit is considered when determin
Updated

2021-02-24 13:48 UTC, ipopescu commented on glossary/U.rst
> +However, the amount only gets transferred to the sender several weeks later, after the unbonding period. If during that period their node exhibits a fault, the unbonded amount can still be slashed.
Done

2021-02-24 13:49 UTC, ipopescu commented on glossary/V.rst
> +Validators are bonded because they are responsible for progressing the system's state as clients use it (e.g., sending deploys). Validators and `stakers <S.html#staker>`_ can lose their bond (be slas
Updated

2021-02-24 13:50 UTC, ipopescu commented on glossary/U.rst
> +Withdrawing money from the Proof-of-Stake (PoS) contract and possibly ceasing to be a validator.
Updated

2021-02-24 13:53 UTC, ipopescu commented on glossary/N.rst
> +#. COMM - contains the logic for message passing between nodes on the network (via TCP) as well as discovering new peers (via Kademlia)
Removed references to Kademlia and fragments containing it such as "discovering new peers (via Kademlia)".

2021-02-24 13:55 UTC, ipopescu commented on glossary/N.rst
> +#. Consensus - contains the logic to update the `blockstore <B.html#blockstore>`_ so that agreement is maintained between nodes. It also contains logic to detect when `deploys <D.html#deploy>`_ commu
Added global state. Removed the sentence about commutation.

2021-02-24 13:56 UTC, ipopescu commented on glossary/N.rst
> +* **Bootstrap node**: a peer node on the P2P network that contains the logic for message passing between nodes on the network (via TCP) and discovering new peers so that they may join the network.
Changed to "trusted node" instead of "bootstrap node".

2021-02-24 13:57 UTC, ipopescu commented on glossary/N.rst
> +* **Bootstrap node**: a peer node on the P2P network that contains the logic for message passing between nodes on the network (via TCP) and discovering new peers so that they may join the network.
Given the later comment, changed to bonded node.

2021-02-24 13:58 UTC, ipopescu commented on glossary/N.rst
> +* **Read-only node**: a type of node on the network that receives and processes blocks but does not create blocks and is not a validator. It is otherwise a fully functioning node, following the conse
Great, updated to use bonded/unbonded nodes.

2021-02-24 14:02 UTC, ipopescu commented on glossary/P.rst
> +The process of following the `consensus <C.html#consensus>`_ algorithm. The primary participants are `validators <V.html#validators>`_.
Added entries for "delegator" and "delegation rate".

**Delegation rate**
Node operators (validators) define a commission that they take in exchange for providing staking services. This commission is represented as a percentage of the rewards that the node operator retains for their services.

**Delegator**
Delegators are users who participate in the platform's security by delegating their tokens to validators, which adds to their weight, and collecting a part of the rewards proportional to their delegations, net of a cut ("delegation rate") that is collected by the validator.

2021-02-24 14:10 UTC, ipopescu commented on glossary/P.rst
> +
I added 2 entries for _private key_, and _secret key_, with this definition: "A cryptographic and confidential key that signs transactions to ensure a valid execution can only do the user's intended operations."

2021-02-24 14:17 UTC, ipopescu commented on glossary/N.rst
> +In `node <N.html#node>`_ COMM - contains the logic for message passing between nodes on the network (via TCP) as well as discovering new peers (via Kademlia).
I moved and updated this entry under T for _trusted node_: 
A bonded node that contains the logic for message passing between nodes on the network (via TCP).

2021-02-24 14:23 UTC, ipopescu commented on glossary/P.rst
> +
Added a new entry for payment code: the WASM program that pays the transaction execution fee.

2021-02-24 14:26 UTC, ipopescu commented on glossary/S.rst
> +A person that deposits tokens in the `proof-of-stake <P.html#proof-of-stake>`_ contract. Sometimes a staker is also a `validator <V.html#validator>`_. Stakers take on the slashing risk in exchange fo
Updated to say that a staker can be a validator or delegator.

2021-02-24 14:52 UTC, ipopescu commented
Ready for a second review.
I addressed the feedback, updated the Validator entry, and added new entries for:
- Ecosystem
- Eviction
- Proof-of-Stake contract
- Rewards
- Runtime
- Transaction fees
- Users

2021-02-25 22:29 UTC, MParlikar requested changes

2021-02-26 10:08 UTC, afck commented on glossary/index.rst
> +=======
Looks like a merge conflict?
```suggestion
```

2021-02-26 10:08 UTC, afck commented on glossary/index.rst
> +>>>>>>> 1829d72 (initial commit)
```suggestion
```
(Or is the whole paragraph supposed to be removed?)

2021-02-26 10:17 UTC, ipopescu commented on glossary/index.rst
> +=======
Yes, resolved, sorry about that!

2021-02-26 10:17 UTC, ipopescu commented on glossary/index.rst
> +>>>>>>> 1829d72 (initial commit)
Somehow this got through without raising a flag. I fixed it with a new commit.

2021-02-26 11:48 UTC, ipopescu commented on glossary/C.rst
> +CSPR is the Casper token pre-defined on the Casper network and used to pay for transaction execution.
Updated the **CSPR** entry and added an entry for **Staking**.

**CSPR**
CSPR is the Casper token pre-defined on the Casper network and used to pay for transaction execution and for `staking <S.html#staking>`_ (securing the network).

**Staking**
A feature of Proof-of-Stake protocols that allows token holders to actively participate in the protocol, thus securing the network. The `Staking Guide <https://docs.casperlabs.io/en/latest/staking/index.html>`_ highlights the steps required to stake the CSPR token on the Casper network.

2021-02-26 12:01 UTC, ipopescu commented on glossary/E.rst
> +Deactivate validators who fail to participate in an era, disabling their bid and suspending their participation until they signal readiness to resume participation by invoking a particular entry poin
Updated the Eviction definition. I also defined a new term  "auction contract", in addition to the auction.

Auction
^^^^^^^
The auction determines the composition of the validator set for each era of the protocol. It is a "first-price" auction (where winning bids become stakes) with a fixed number of spots, chosen to balance security with performance. Because rewards are proportional to the stake, it is expected that this competitive mechanism will provide a powerful impetus for staking as many tokens as possible.

Auction contract
^^^^^^^^^^^^^^^^
The auction contract acts as a front-end user interface to the `auction <auction>`_ by accepting bids from validators and delegators directly. It also contains the logic necessary for carrying out the auction.

2021-02-26 12:20 UTC, ipopescu commented on glossary/B.rst
> +The first block that is less than 11 days way from the beginning of an era. It defines the new era's validator set, weights, but not yet the leader schedule. Each block between the booking block and
Thanks, @afck & @MParlikar. I've updated the _booking block_ definition and added a new definition for the _auction delay._ 

**Booking block**
The first block in an era, which considers the `auction delay <A.html#auction-delay>`_. In other words, the last block of era N is the booking block for era N + `auction delay <A.html#auction-delay>`_ + 1, where the auction delay is the number of full eras that pass between the booking block and the era whose validator set it defines. The auction delay is configurable and can be several eras.

**Auction delay**
The number of full eras that pass between the `booking block <B.html#booking-block>`_ and the era whose validator set it defines. The auction delay is configurable and can be several eras.

2021-02-26 13:10 UTC, ipopescu commented
Update on 2/26
-  Addressed review feedback.
- Updated the **gas**, **cspr**, **booking block**, and **eviction** definitions, and added new entries for: **auction contract**, **auction delay**, **staking**, and **operator**.
- Fixed the sorting order in file B and a few other entries.
- Removed a few duplicates.
- Combed through everything one more time and ran Grammarly.
- Checked for any statements that did not sound configurable (such as 11 days in the booking block).

2021-02-26 18:12 UTC, afck reviewed
Looks great! :+1: 

Please take my comments only as _suggestions_; I'm not sure what exactly should be the scope of the glossary, and whether everyone agrees with what I wrote. In particular, someone more familiar with the contract runtime should review this as well.

2021-02-26 18:12 UTC, afck commented on glossary/S.rst
> +
Should we remove that? We don't currently do sharding.

2021-02-26 18:12 UTC, afck commented on glossary/S.rst
> +In Proof-of-Stake, the deposit acts as collateral. The validator guarantees that it correctly follows the protocol. If the validator node creates an equivocation or fails to send messages for too lon
```suggestion
In Proof-of-Stake, the deposit acts as collateral. The validator guarantees that it correctly follows the protocol. If the validator node violates the protocol, the deposited amount gets "slashed," i.e., removed.
```

2021-02-26 18:12 UTC, afck commented on glossary/S.rst
> +A person that deposits tokens in the `proof-of-stake <P.html#proof-of-stake>`_ contract. Sometimes a staker is also a `validator <V.html#validator>`_ or a `delegator <D.html#delegator>`_. Stakers tak
Not sure whether we still have a (user-visible) distinction of "proof of stake contract" vs. "auction contract", or we should just always use the term "auction contract"?

2021-02-26 18:12 UTC, afck commented on glossary/T.rst
> +The feature-complete, decentralized public Casper platform for testing.
Do we still need entries for "devnet" and "testnet" — or should we have one for "delta" now instead?

2021-02-26 18:12 UTC, afck commented on glossary/T.rst
> +*  **Nonce** – [mandatory] the number which prevents replay attacks by making each signature valid for a single execution
Obsolete?
(But maybe other fields where added?)

2021-02-26 18:12 UTC, afck commented on glossary/T.rst
> +*  **Block hook** - [optional] semantic dependency of this transaction, expressed as a hash of a block that is
Are dependencies specified as _deploy_ hashes instead of _block_ hashes now?

2021-02-26 18:12 UTC, afck commented on glossary/T.rst
> +*  **Signature** – [mandatory] must be done via a private or secret key (applied over the payment code, session code, conversion rate, or nonce), to ensure the correct execution of intended operation
```suggestion
*  **Signature** – [mandatory] must be done via a secret key (applied over the payment code, session code, conversion rate, or nonce), to ensure the correct execution of intended operations
```
(I think it's less confusing to consistently use "secret key". Otherwise it looks as if those were distinct keys.)

2021-02-26 18:12 UTC, afck commented on glossary/V.rst
> +Validators are bonded because they are responsible for progressing the system's state as clients use it (e.g., sending deploys). Validators and `stakers <S.html#staker>`_ can lose their bond (be slas
Are they still synonymous? Maybe we use both terms in multiple, slightly different meanings sometimes. :confused:

2021-02-26 18:12 UTC, afck commented on implementation/p2p.rst
> +-  ``known_block_hashes`` can be supplied by the caller to provide an early exit
At a glance, it looks like most of this file is outdated (refers to the old Scala code).

2021-02-26 18:43 UTC, ashok-cl requested changes

2021-02-26 18:43 UTC, ashok-cl commented on glossary/N.rst
> +Anyone who wishes to run node infrastructure on the Casper network either as a standalone private network, or as part of the public network. Synonymous to a `validator <V.html#validator>`_.
@MParlikar - not sure we need to or should specifically mention 'private network' here.

2021-02-26 18:43 UTC, ashok-cl commented on glossary/P.rst
> +The process of following the `consensus <C.html#consensus>`_ algorithm. The primary participants are `validators <V.html#validator>`_ and `delegators <D.html#delegator>`_.
_The primary participants are `validators <V.html#validator>`_ and `delegators <D.html#delegator>`_._

Maybe more accurate to say 'the primary participants are validators that are bonded with their stake and are part of the validator set for that particular era. Delegators participate indirectly by delegating their tokens to one or more of these validators and contribute by increasing the total stake that goes towards ensuring security of the network' @afck

2021-02-26 18:43 UTC, ashok-cl commented on glossary/P.rst
> +The Casper platform defines only one token which one can pay for transaction execution. Presently this is called `CSPR <C.html#cspr>`_.
The Casper platform defines only one token with which one can pay for transaction execution and the same is also used for staking to secure the network and earn rewards.

2021-02-26 18:43 UTC, ashok-cl commented on glossary/P.rst
> +The block proposed by the leader, which the consensus processes (in `highway <H.html#highway>`_). Only after consensus is complete, the proto block is executed and the global state is updated.
Maybe add: 
A leader is selected from the validator set of that era for each round and the chance of getting selected as a leader is in proportion to their stake in that era.

2021-02-26 18:43 UTC, ashok-cl commented on glossary/S.rst
> +In Proof-of-Stake, the deposit acts as collateral. The validator guarantees that it correctly follows the protocol. If the validator node creates an equivocation or fails to send messages for too lon
_fails to send messages for too long_ - This is not true. They only get evicted and don't receive any rewards. @afck

2021-02-26 18:50 UTC, afck commented on glossary/N.rst
> +* **Bonded node**: any node that can be trusted on the network.
That's true, "can be trusted" is a bit vague.

2021-02-26 18:51 UTC, afck commented on glossary/E.rst
> +The Highway protocol execution is split into eras, and at the start of each era, every validator is initialized. Validators are forced to store the whole DAG, even the units that were created at the
Yes, I made a proposal above.
I agree, it's a config setting, and probably not 1000 blocks.

2021-02-26 18:52 UTC, afck commented on glossary/B.rst
> +Block finality in the `Highway <H.html#highway>`_ protocol is expressed by a fraction of nodes that would need to break the protocol rules in order for a block to be reverted. During periods of hones
I made a proposal above.
Yes, a finalized block's fault tolerance can go higher than 1/3.

2021-03-03 11:59 UTC, ipopescu commented on glossary/B.rst
> +
Removed with commit 69fbce78c802ed8ee5691e640344202208ab8ae5.

2021-03-03 11:59 UTC, ipopescu commented on glossary/B.rst
> +#. A data structure containing a collection of transactions. Blocks form the BlockDAG and, as such, are a primary structure of the blockchain.
@afck removed block DAG from all explanations with commit 832818c6bf4efbc40a251d41f077c5a97ec2b65a.

2021-03-03 12:03 UTC, ipopescu commented on glossary/B.rst
> +Each block points to his parents (one or many) and justification blocks (one or many). Parents are a subset of justifications. An exception is the Genesis block, which has no parents and no justifica
Updated with commit cc6a6f5f372d8f27f8b0578873caf2babfb2a5ad. Just fyi, I couldn't apply the commit directly (due to a prior merge from master), but I appreciate this format!

2021-03-03 12:49 UTC, ipopescu commented on glossary/B.rst
> +Block creation is always followed by "block proposal" (see below) because it does not make sense to create a block without sending it out to the network. Note that only validators can create valid bl
@afck submitted an updated definition for block creation with commit 525219238d13c35510c5b756aa9eb2297842c085. I also added 2 related definitions for **root hash** and **Merkle tree** with this commit.

2021-03-03 12:58 UTC, ipopescu commented on glossary/V.rst
> +Validators are bonded because they are responsible for progressing the system's state as clients use it (e.g., sending deploys). Validators and `stakers <S.html#staker>`_ can lose their bond (be slas
You're right, one can operate a node without being a validator. I will take this out.

2021-03-03 13:04 UTC, ipopescu commented on implementation/p2p.rst
> +-  ``known_block_hashes`` can be supplied by the caller to provide an early exit
This file will be updated as part of https://github.com/CasperLabs/docs/pull/133.

2021-03-03 13:09 UTC, ipopescu commented on glossary/B.rst
> +* Bonds map matches the PoS contract state
Agreed. Keeping simple is better in a glossary. Will remove the list.

2021-03-03 14:16 UTC, ipopescu commented on glossary/B.rst
> +The first block in an era, which considers the `auction delay <A.html#auction-delay>`_. In other words, the last block of era N is the booking block for era N + `auction delay <A.html#auction-delay>`
Incorporated the suggestion

2021-03-03 14:20 UTC, ipopescu commented on glossary/C.rst
> +An algorithm used to mandate agreement on the `blockDAG <B.html#blockdag>`_ between all nodes. The blockDAG, although being built in a decentralized way, eventually converges so that all nodes eventu
Updated to include suggestion

2021-03-03 14:20 UTC, ipopescu commented on glossary/D.rst
> +In the Highway protocol, validators exchange messages in order to reach consensus on proposed blocks and hence validate one of many branches of the produced blockchain. As a way of capturing and spre
Agreed. Let's keep the glossary simple. Removed this section.

2021-03-03 14:29 UTC, ipopescu commented on glossary/E.rst
> +The Highway protocol execution is split into eras, and at the start of each era, every validator is initialized. Validators are forced to store the whole DAG, even the units created at the beginning
Incorporated the suggestion. Yes, we can mention the era length when it's decided.

2021-03-03 14:30 UTC, ipopescu commented on glossary/F.rst
> +In the Highway protocol, if an honest validator reaches finality with confidence threshold t >= f for a given valid block B, then no honest validator will ever reach finality with confidence threshol
Removed

2021-03-03 14:45 UTC, ipopescu commented on glossary/C.rst
> +CSPR is the Casper token pre-defined on the Casper network and used to pay for transaction execution and for `staking <S.html#staking>`_ (securing the network).
Included. "The total number of CSPR tokens is 10 billion."

2021-03-03 14:51 UTC, ipopescu commented on glossary/B.rst
> +Block finality in the `Highway <H.html#highway>`_ protocol is expressed by a fraction of nodes that would need to break the protocol rules in order for a block to be reverted. During periods of hones
Feedback incorporated

2021-03-03 14:52 UTC, ipopescu commented on glossary/G.rst
> +The first `block <B.html#block>`_ in the `blockchain <B.html#blockchain>`_. P-future-chain of Genesis includes all blocks ever created.
Incorporated this suggestion

2021-03-03 14:56 UTC, ipopescu commented on glossary/G.rst
> +For every `block <B.html#block>`_ B in the `blockDAG <B.html#blockdag>`_, one can compute the `global state <G.html#global-state>`_ achieved by executing all `transactions <T.html#transaction>`_ in t
Feedback incorporated

2021-03-03 15:00 UTC, ipopescu commented on glossary/I.rst
> +^^^^^^^^^^^
Let's make it empty, and keep all the letters for easier navigation. Removed "coming soon" from all empty entries.

2021-03-03 15:03 UTC, ipopescu commented on glossary/N.rst
> +#. Storage - this is where the blockstore and the global state are stored.
Removed to keep it clean and simple.

2021-03-03 15:04 UTC, ipopescu commented on glossary/N.rst
> +The number that prevents replay attacks by making each signature valid for a single execution.
Removed nonce and will follow up on TTL and dependencies.

2021-03-03 15:05 UTC, ipopescu commented on glossary/P.rst
> +The process of following the `consensus <C.html#consensus>`_ algorithm. The primary participants are `validators <V.html#validator>`_ and `delegators <D.html#delegator>`_.
Removed delegators. Kept validators as primary consensus participants.

2021-03-03 15:08 UTC, ipopescu commented on glossary/P.rst
> +The Casper platform defines only one token which one can pay for transaction execution. Presently this is called `CSPR <C.html#cspr>`_.
Updated to "with which one can pay".

2021-03-03 15:13 UTC, ipopescu commented on glossary/P.rst
> +Proof of stake (PoS) is a type of consensus mechanism by which a cryptocurrency blockchain network achieves distributed consensus. The voting power is proportional to the number of tokens (digital cu
Agreed. I have seen Proof-of-Stake more often and will use that. I will adopt your explanation and put it up for a final review.

2021-03-03 15:15 UTC, ipopescu commented on glossary/R.rst
> +Validators receive rewards for participating in consensus by voting on blocks sending finality signatures (finalizing blocks). There is no precise per-block reward. Rewards are split proportionally a
Updated

2021-03-03 15:16 UTC, ipopescu commented on glossary/S.rst
> +
Removed

2021-03-03 15:21 UTC, ipopescu commented on glossary/R.rst
> +The Casper runtime layer encompasses deployment and execution of `smart contracts <S.html#smart-contracts>`_, `session code <S.html#session-code>`_, and other activity that performs computation on th
Removed. Renamed _Casper runtime_ to _Contract runtime_. I will take the second suggestion in a separate ticket.

2021-03-03 15:22 UTC, ipopescu commented on glossary/S.rst
> +In Proof-of-Stake, the deposit acts as collateral. The validator guarantees that it correctly follows the protocol. If the validator node creates an equivocation or fails to send messages for too lon
Updated

2021-03-03 15:23 UTC, ipopescu commented on glossary/T.rst
> +The feature-complete, decentralized public Casper platform for testing.
For the sake of simplicity and since we are close to mainnet, I will remove devnet and testnet. I am not sure about Delta, I will find out.

2021-03-03 15:26 UTC, ipopescu commented on glossary/B.rst
> +Block finality in the `Highway <H.html#highway>`_ protocol is expressed by a fraction of nodes that would need to break the protocol rules in order for a block to be reverted. During periods of hones
Updated

2021-03-03 15:27 UTC, ipopescu commented on glossary/E.rst
> +The Highway protocol execution is split into eras, and at the start of each era, every validator is initialized. Validators are forced to store the whole DAG, even the units that were created at the
Updated

2021-03-03 15:33 UTC, ipopescu commented on glossary/P.rst
> +The block proposed by the leader, which the consensus processes (in `highway <H.html#highway>`_). Only after consensus is complete, the proto block is executed and the global state is updated.
Added.

2021-03-03 15:37 UTC, ipopescu commented on glossary/S.rst
> +In Proof-of-Stake, the deposit acts as collateral. The validator guarantees that it correctly follows the protocol. If the validator node creates an equivocation or fails to send messages for too lon
Updated to: "The validator guarantees that it correctly follows the protocol. If the validator node violates the protocol, the deposited amount gets "slashed," i.e., a part of it is removed."

2021-03-03 15:39 UTC, ipopescu commented on glossary/P.rst
> +The Casper platform defines only one token which one can pay for transaction execution. Presently this is called `CSPR <C.html#cspr>`_.
I decided to point this directly CSPR by saying "See CSPR."

2021-03-03 15:52 UTC, ipopescu commented
Addressed most feedback. I have a few open questions which I will summarise below and follow up.

What are the current mandatory fields in a transaction?
https://github.com/CasperLabs/docs/pull/124#discussion_r583822415 

Do we use “block store” or “block storage”?
https://github.com/CasperLabs/docs/pull/124#discussion_r583788402 

Definition of a Deploy TTL and a Dependency? Coming from this comment:
https://github.com/CasperLabs/docs/pull/124#discussion_r583811743 

Are dependencies specified as deploy hashes instead of block hashes now?
https://github.com/CasperLabs/docs/pull/124#discussion_r583822660 

Do we still have a (user-visible) distinction of "proof of stake contract" vs. "auction contract", or we should just always use the term "auction contract"?
https://github.com/CasperLabs/docs/pull/124#discussion_r583821277 

Do we want a definition for Delta in the glossary?
https://github.com/CasperLabs/docs/pull/124#discussion_r586508208 

Not sure we need to or should specifically mention 'private network' in the Node operator definition: anyone who wishes to run node infrastructure on the Casper network either as a standalone private network, or as part of the public network.
https://github.com/CasperLabs/docs/pull/124#discussion_r583820552 

If anyone disagrees with Andreas’ controversial opinion regarding Proof-of-Stake, let me know. Otherwise I will go with his definition.
https://github.com/CasperLabs/docs/pull/124#discussion_r583815535

2021-03-03 16:10 UTC, EdHastingsCasperLabs commented on glossary/T.rst
> +*  **Nonce** – [mandatory] the number which prevents replay attacks by making each signature valid for a single execution
Nonce is definitely obsolete...it was even obsolete in the scala hybrid era.

2021-03-03 16:14 UTC, EdHastingsCasperLabs commented on glossary/V.rst
> +Validators are bonded because they are responsible for progressing the system's state as clients use it (e.g., sending deploys). Validators and `stakers <S.html#staker>`_ can lose their bond (be slas
Any one running a node is an _operator_ 

An operator that has staked a bid but does not currently have a validator slot is a _staked operator_

An operator who's bid has won a validator slot in the auction for a specific era is a _validator_ in that era. 

It is common for a staked operator to win an auction slot for many eras in a row, and thus be a validator for a range of eras.

2021-03-03 16:26 UTC, EdHastingsCasperLabs commented on glossary/T.rst
> +Transaction
This is a _Deploy_ in our system.

Suggest this should be moved under D, and here under Transaction link to Deploy "See `Deploy <D.html#deploy>"

2021-03-07 18:21 UTC, ipopescu commented on glossary/F.rst
> +Finality theorem
Andreas suggested to remove the finality theorem all-together. Those interested can read the paper.

2021-03-07 18:22 UTC, ipopescu commented on glossary/L.rst
> +In the Highway protocol, for every confidence threshold 0 <= t < n/3 , if f <= t and c < (n-3t)/2, then the chain of blocks finalized with confidence t grows indefinitely for each honest validator.
Removed the _liveness theorem_, and those interested can read the paper. We do cover _liveness_ separately. Discussed this with Andreas.

2021-03-07 18:24 UTC, ipopescu commented on glossary/N.rst
> +* **Bonded node**: any node that can be trusted on the network.
Updated based on Ashok's suggestion

2021-03-07 18:25 UTC, ipopescu commented on glossary/T.rst
> +*  **Nonce** – [mandatory] the number which prevents replay attacks by making each signature valid for a single execution
Removed "nonce". I still need to find out if the other fields are correct.

2021-03-07 18:36 UTC, ipopescu commented on glossary/T.rst
> +Transaction
Done. This also resolves the above comment about the transaction fields.

2021-03-07 18:38 UTC, ipopescu commented on glossary/T.rst
> +*  **Nonce** – [mandatory] the number which prevents replay attacks by making each signature valid for a single execution
Pointed Transaction to Deploy, and kept the simpler Deploy definition.

2021-03-07 18:40 UTC, ipopescu commented on glossary/T.rst
> +The feature-complete, decentralized public Casper platform for testing.
Let's remove Delta and focus on mainnet.

2021-03-07 19:22 UTC, ipopescu commented on glossary/N.rst
> +Anyone who wishes to run node infrastructure on the Casper network either as a standalone private network, or as part of the public network. Synonymous to a `validator <V.html#validator>`_.
Removed the mention of private network and added a new definition for Operator based on Ed's suggestion.

2021-03-07 19:23 UTC, ipopescu commented on glossary/V.rst
> +Validators are bonded because they are responsible for progressing the system's state as clients use it (e.g., sending deploys). Validators and `stakers <S.html#staker>`_ can lose their bond (be slas
Thanks @EdHastingsCasperLabs! I added a new entry for _Operator_ with these definitions. I pointed "node operator" to "operator".

2021-03-07 19:47 UTC, ipopescu commented on glossary/B.rst
> +Blockstore
I see that in the _node operator/setup.rst_ we use block store. I will use this for now until I hear otherwise.

2021-03-07 19:51 UTC, ipopescu commented on glossary/S.rst
> +A person that deposits tokens in the `proof-of-stake <P.html#proof-of-stake>`_ contract. Sometimes a staker is also a `validator <V.html#validator>`_ or a `delegator <D.html#delegator>`_. Stakers tak
I see the following explanation in the Execution Semantics: "Payment code ultimately provides its payment by performing a token transfer into the proof-of-stake contract’s payment purse. If payment is not given or not enough is transferred, then payment execution is not considered successful." 
https://docs.casperlabs.io/en/latest/implementation/execution-semantics.html?highlight=payment%20code#payment-code
I will keep the "proof of stake contract" until I hear otherwise.

2021-03-07 19:52 UTC, ipopescu commented on glossary/T.rst
> +*  **Block hook** - [optional] semantic dependency of this transaction, expressed as a hash of a block that is
Removed these details.

2021-03-07 19:59 UTC, ipopescu commented
This PR is ready for a final review and hopefully a merge. There are 3 open comments, but maybe we can address them right before the merge.

1. Should we use block store or block storage? (comment https://github.com/CasperLabs/docs/pull/124#discussion_r583788402)
2. Should we have definitions for a deployment TTL and deploy dependencies? (comment https://github.com/CasperLabs/docs/pull/124#discussion_r583811743)
3. Do we still have a (user-visible) distinction of "proof of stake contract" vs. "auction contract", or we should just always use the term "auction contract"? I decided to keep it until I hear otherwise. It's mentioned in the execution semantics. (comment https://github.com/CasperLabs/docs/pull/124#discussion_r583821277)

2021-03-08 22:24 UTC, MParlikar approved these changes
Great job

2021-03-09 16:44 UTC, ashok-cl approved these changes

2021-03-09 19:07 UTC, merged