NDRS-802: Describe networking process
CasperLabs/docs pull request #133
Opened 2021-03-01 14:24 UTC by marc-casperlabs

This updates the networking documentation to make it reflect the current state of the code, only including lower level networking.

2021-03-05 14:21 UTC, ipopescu approved these changes
Thanks so much for these updates! I pushed a commit with small updates:
1. Ran it through the Grammarly tool
2. Removed the mention of the DAG

2021-03-06 02:01 UTC, EdHastingsCasperLabs requested changes
I'm concerned about some of the formatting changes, which may have been the result of some kind of auto-correction.

2021-03-06 12:45 UTC, ipopescu commented
@EdHastingsCasperLabs I made all the editing changes manually, after which I double checked them to make sure the meaning is maintained. I did use an assistive software for editing (Grammarly), but all the changes were intentional. If you guys are more comfortable with the original, that works too, as long as we remove the mention of the DAG. Andreas recommends to use blockchain instead.

2021-03-07 22:11 UTC, marc-casperlabs commented on implementation/p2p.rst
> +3. For every node shown as already infected, add another random node outside to `T` and send it `M,` again noting the response.
@ipopescu I think Ed's referring to these changes in particular:

```
`M,`
```

which will render the comma the same way it renders the M, in this case in italics.

This used to be

```
`M`, 
```

instead (note the order of the backtick and the comma). I use the backticks to mark symbols here (maybe I should have used `$M$` instead?), and the comma is not part of the symbol `M`.

Now, admittedly, with our currently style, the visible difference is small, barely a few pixels (I checked :) :

![nothatdifferent](https://user-images.githubusercontent.com/63730123/110256486-6ec41480-7f99-11eb-9f1f-46e1d86554c1.png)


), but this is only because of our currently chosen stylesheet -- should we ever switch it, this might look bad (e.g. my editor renders this as follows:

![MM](https://user-images.githubusercontent.com/63730123/110256645-3c66e700-7f9a-11eb-80b9-d73333af5596.png)

)

2021-03-07 22:12 UTC, marc-casperlabs commented
I added a few comments to clarify what I think the issue is. I assumed those changes were not introduced manually, making me a little nervous about what might have been altered as well, sorry about that.

2021-03-08 10:15 UTC, ipopescu commented
> I added a few comments to clarify what I think the issue is. I assumed those changes were not introduced manually, making me a little nervous about what might have been altered as well, sorry about that.

Thank you, Mark! I understand now, and I submitted a fix. Sorry, I made that mistake manually (being used to that pattern). When I checked the docs locally, they looked good. I'll be more careful with these italicised letters in the future and with special symbols. Just fyi: it seems that we can also use the star for italics (*a*) and the double star for bold: **a**.

2021-03-08 17:49 UTC, EdHastingsCasperLabs approved these changes

2021-03-09 10:10 UTC, merged