DSL documentation update
CasperLabs/docs pull request #135
Opened 2021-03-06 22:02 UTC by ipopescu

Changes in this PR:
1. I have updated the DSL docs based on [Ramsin's new tutorial](https://docs.google.com/document/d/1semeumn2KuZ6D3OMP6wRGWfCHso8GeeyEduUlL60XAc/edit?pli=1#) and our meeting with Karan. 
2. The previous DSL files are now in a hidden "archived" folder, since the updates were fairly large. 
3. I moved the DSL section right after the Getting Started guide, based on Medha's feedback. Also, I moved the NCTL guide lower, right before the deployment section (also based on Medha's feedback).
4. I consolidated the 2 testing guides into one testing section, to organize the left side bar.

Attached are the pdf files for those who wish to read without running the docs locally. Thanks!
- [dsl-page1.pdf](https://github.com/CasperLabs/docs/files/6096175/dsl-page1.pdf)
- [dsl-page2.pdf](https://github.com/CasperLabs/docs/files/6096176/dsl-page2.pdf)
- [dsl-page3.pdf](https://github.com/CasperLabs/docs/files/6096177/dsl-page3.pdf)

<img width="1440" alt="Screenshot 2021-03-06 at 22 59 14" src="https://user-images.githubusercontent.com/4185994/110222061-f8a7ab00-7ecf-11eb-9ed1-3d9758bc268b.png">

2021-03-10 05:55 UTC, ramujin commented on dapp-dev-guide/contract-dsl/advanced.rst
> +If you examine the repository contents, you’ll see that there is a Makefile. This is an alternative to using a build script, as we did in the `Getting guide <https://docs.casperlabs.io/en/latest/dapp
"Getting guide" should be renamed to "Getting Started Guide"

2021-03-10 05:58 UTC, ramujin reviewed
Just found one small typo, but everything else looks good!

2021-03-10 11:07 UTC, ipopescu commented on dapp-dev-guide/contract-dsl/advanced.rst
> +If you examine the repository contents, you’ll see that there is a Makefile. This is an alternative to using a build script, as we did in the `Getting guide <https://docs.casperlabs.io/en/latest/dapp
Done! Thanks for catching this!

2021-03-10 11:09 UTC, ipopescu commented
Addressed the small correction needed and merged _master_ into the branch. The PR should be ready now.

2021-03-11 01:11 UTC, ramujin commented
Looks ready to me!

2021-03-11 16:17 UTC, MParlikar requested changes
We should focus on testing via Units and running them with cargo-casper.

2021-03-11 21:55 UTC, ipopescu commented on dapp-dev-guide/testing/index.rst
> +   setup-nctl
The testing section was still there, but in a testing folder. Since this setup wasn't clear, I have reverted back to the original structure with a new commit 3773cababd530395e74e3b620dd7c13778b91913. I removed the testing folder, and left the testing.rst and nctl-setup.rst in the main dApp folder.

<img width="1156" alt="1" src="https://user-images.githubusercontent.com/4185994/110860307-e5745100-82bc-11eb-9ccb-9b5d94b2f700.png">
<img width="1005" alt="2" src="https://user-images.githubusercontent.com/4185994/110860310-e60ce780-82bc-11eb-8d9e-6f5528233813.png">
<img width="1118" alt="3" src="https://user-images.githubusercontent.com/4185994/110860312-e6a57e00-82bc-11eb-9aba-f34e4b1b569f.png">

2021-03-11 22:00 UTC, ipopescu commented
The testing section needs some additional details and examples. I will address this in ECO.... But for the purpose of this PR, for the DSL guide, I have reverted to the original structure that brings the testing.rst file right after the writing-contracts section.

2021-03-20 22:51 UTC, MParlikar approved these changes

2021-03-20 22:51 UTC, merged